// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveAction(arg1) {
  return window['go']['main']['App']['ApproveAction'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckAuthStatus() {
  return window['go']['main']['App']['CheckAuthStatus']();
}

export function CreateThread(arg1) {
  return window['go']['main']['App']['CreateThread'](arg1);
}

export function GetAppDetail(arg1) {
  return window['go']['main']['App']['GetAppDetail'](arg1);
}

export function GetScreenshots(arg1) {
  return window['go']['main']['App']['GetScreenshots'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersionMetadata(arg1) {
  return window['go']['main']['App']['GetVersionMetadata'](arg1);
}

export function ListApprovals() {
  return window['go']['main']['App']['ListApprovals']();
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function QueueMutation(arg1) {
  return window['go']['main']['App']['QueueMutation'](arg1);
}

export function RejectAction(arg1) {
  return window['go']['main']['App']['RejectAction'](arg1);
}

export function ResolveASC() {
  return window['go']['main']['App']['ResolveASC']();
}

export function RunASCCommand(arg1) {
  return window['go']['main']['App']['RunASCCommand'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}
