package asc

import (
	"reflect"
	"testing"
)

func TestValidWebhookEventTypesMatchesOpenAPI(t *testing.T) {
	want := []string{
		"ALTERNATIVE_DISTRIBUTION_PACKAGE_AVAILABLE_UPDATED",
		"ALTERNATIVE_DISTRIBUTION_PACKAGE_VERSION_CREATED",
		"ALTERNATIVE_DISTRIBUTION_TERRITORY_AVAILABILITY_UPDATED",
		"APP_STORE_VERSION_APP_VERSION_STATE_UPDATED",
		"BACKGROUND_ASSET_VERSION_APP_STORE_RELEASE_STATE_UPDATED",
		"BACKGROUND_ASSET_VERSION_EXTERNAL_BETA_RELEASE_STATE_UPDATED",
		"BACKGROUND_ASSET_VERSION_INTERNAL_BETA_RELEASE_CREATED",
		"BACKGROUND_ASSET_VERSION_STATE_UPDATED",
		"BETA_FEEDBACK_CRASH_SUBMISSION_CREATED",
		"BETA_FEEDBACK_SCREENSHOT_SUBMISSION_CREATED",
		"BUILD_BETA_DETAIL_EXTERNAL_BUILD_STATE_UPDATED",
		"BUILD_UPLOAD_STATE_UPDATED",
	}
	if !reflect.DeepEqual(ValidWebhookEventTypes, want) {
		t.Fatalf("ValidWebhookEventTypes = %#v, want %#v", ValidWebhookEventTypes, want)
	}
}
