package asc

// IntegerRange represents an inclusive integer range.
type IntegerRange struct {
	Minimum *int `json:"minimum,omitempty"`
	Maximum *int `json:"maximum,omitempty"`
}

// NewIntegerRange builds an IntegerRange with both bounds set.
func NewIntegerRange(minimum, maximum int) IntegerRange {
	return IntegerRange{
		Minimum: &minimum,
		Maximum: &maximum,
	}
}

// SubscriptionOfferDuration represents subscription offer durations.
type SubscriptionOfferDuration string

const (
	SubscriptionOfferDurationThreeDays   SubscriptionOfferDuration = "THREE_DAYS"
	SubscriptionOfferDurationOneWeek     SubscriptionOfferDuration = "ONE_WEEK"
	SubscriptionOfferDurationTwoWeeks    SubscriptionOfferDuration = "TWO_WEEKS"
	SubscriptionOfferDurationOneMonth    SubscriptionOfferDuration = "ONE_MONTH"
	SubscriptionOfferDurationTwoMonths   SubscriptionOfferDuration = "TWO_MONTHS"
	SubscriptionOfferDurationThreeMonths SubscriptionOfferDuration = "THREE_MONTHS"
	SubscriptionOfferDurationSixMonths   SubscriptionOfferDuration = "SIX_MONTHS"
	SubscriptionOfferDurationOneYear     SubscriptionOfferDuration = "ONE_YEAR"
)

// SubscriptionOfferMode represents subscription offer billing modes.
type SubscriptionOfferMode string

const (
	SubscriptionOfferModePayAsYouGo SubscriptionOfferMode = "PAY_AS_YOU_GO"
	SubscriptionOfferModePayUpFront SubscriptionOfferMode = "PAY_UP_FRONT"
	SubscriptionOfferModeFreeTrial  SubscriptionOfferMode = "FREE_TRIAL"
)

// SubscriptionOfferEligibility represents how offer codes interact with intro offers.
type SubscriptionOfferEligibility string

const (
	SubscriptionOfferEligibilityStackWithIntroOffers SubscriptionOfferEligibility = "STACK_WITH_INTRO_OFFERS"
	SubscriptionOfferEligibilityReplaceIntroOffers   SubscriptionOfferEligibility = "REPLACE_INTRO_OFFERS"
)

// SubscriptionCustomerEligibility represents eligible customer types for offers.
type SubscriptionCustomerEligibility string

const (
	SubscriptionCustomerEligibilityNew      SubscriptionCustomerEligibility = "NEW"
	SubscriptionCustomerEligibilityExisting SubscriptionCustomerEligibility = "EXISTING"
	SubscriptionCustomerEligibilityExpired  SubscriptionCustomerEligibility = "EXPIRED"
)

// WinBackOfferPriority represents win-back offer priority.
type WinBackOfferPriority string

const (
	WinBackOfferPriorityHigh   WinBackOfferPriority = "HIGH"
	WinBackOfferPriorityNormal WinBackOfferPriority = "NORMAL"
)

// WinBackOfferPromotionIntent represents promotion intent for win-back offers.
type WinBackOfferPromotionIntent string

const (
	WinBackOfferPromotionNotPromoted            WinBackOfferPromotionIntent = "NOT_PROMOTED"
	WinBackOfferPromotionUseAutoGeneratedAssets WinBackOfferPromotionIntent = "USE_AUTO_GENERATED_ASSETS"
)

// WinBackOfferAttributes describes a win-back offer.
type WinBackOfferAttributes struct {
	ReferenceName                                       string                       `json:"referenceName,omitempty"`
	OfferID                                             string                       `json:"offerId,omitempty"`
	Duration                                            SubscriptionOfferDuration    `json:"duration,omitempty"`
	OfferMode                                           SubscriptionOfferMode        `json:"offerMode,omitempty"`
	PeriodCount                                         int                          `json:"periodCount,omitempty"`
	CustomerEligibilityPaidSubscriptionDurationInMonths int                          `json:"customerEligibilityPaidSubscriptionDurationInMonths,omitempty"`
	CustomerEligibilityTimeSinceLastSubscribedInMonths  *IntegerRange                `json:"customerEligibilityTimeSinceLastSubscribedInMonths,omitempty"`
	CustomerEligibilityWaitBetweenOffersInMonths        *int                         `json:"customerEligibilityWaitBetweenOffersInMonths,omitempty"`
	StartDate                                           string                       `json:"startDate,omitempty"`
	EndDate                                             *string                      `json:"endDate,omitempty"`
	Priority                                            WinBackOfferPriority         `json:"priority,omitempty"`
	PromotionIntent                                     *WinBackOfferPromotionIntent `json:"promotionIntent,omitempty"`
}

// WinBackOfferCreateAttributes describes attributes for creating a win-back offer.
type WinBackOfferCreateAttributes struct {
	ReferenceName                                       string                       `json:"referenceName"`
	OfferID                                             string                       `json:"offerId"`
	Duration                                            SubscriptionOfferDuration    `json:"duration"`
	OfferMode                                           SubscriptionOfferMode        `json:"offerMode"`
	PeriodCount                                         int                          `json:"periodCount"`
	CustomerEligibilityPaidSubscriptionDurationInMonths int                          `json:"customerEligibilityPaidSubscriptionDurationInMonths"`
	CustomerEligibilityTimeSinceLastSubscribedInMonths  IntegerRange                 `json:"customerEligibilityTimeSinceLastSubscribedInMonths"`
	CustomerEligibilityWaitBetweenOffersInMonths        *int                         `json:"customerEligibilityWaitBetweenOffersInMonths,omitempty"`
	StartDate                                           string                       `json:"startDate"`
	EndDate                                             *string                      `json:"endDate,omitempty"`
	Priority                                            WinBackOfferPriority         `json:"priority"`
	PromotionIntent                                     *WinBackOfferPromotionIntent `json:"promotionIntent,omitempty"`
}

// WinBackOfferUpdateAttributes describes attributes for updating a win-back offer.
type WinBackOfferUpdateAttributes struct {
	CustomerEligibilityPaidSubscriptionDurationInMonths *int                         `json:"customerEligibilityPaidSubscriptionDurationInMonths,omitempty"`
	CustomerEligibilityTimeSinceLastSubscribedInMonths  *IntegerRange                `json:"customerEligibilityTimeSinceLastSubscribedInMonths,omitempty"`
	CustomerEligibilityWaitBetweenOffersInMonths        *int                         `json:"customerEligibilityWaitBetweenOffersInMonths,omitempty"`
	StartDate                                           *string                      `json:"startDate,omitempty"`
	EndDate                                             *string                      `json:"endDate,omitempty"`
	Priority                                            *WinBackOfferPriority        `json:"priority,omitempty"`
	PromotionIntent                                     *WinBackOfferPromotionIntent `json:"promotionIntent,omitempty"`
}

// WinBackOfferCreateRelationships describes relationships for win-back offers.
type WinBackOfferCreateRelationships struct {
	Subscription Relationship     `json:"subscription"`
	Prices       RelationshipList `json:"prices"`
}

// WinBackOfferCreateData is the data portion of a create request.
type WinBackOfferCreateData struct {
	Type          ResourceType                    `json:"type"`
	Attributes    WinBackOfferCreateAttributes    `json:"attributes"`
	Relationships WinBackOfferCreateRelationships `json:"relationships"`
}

// WinBackOfferCreateRequest is a request to create a win-back offer.
type WinBackOfferCreateRequest struct {
	Data     WinBackOfferCreateData          `json:"data"`
	Included []WinBackOfferPriceInlineCreate `json:"included,omitempty"`
}

// WinBackOfferUpdateData is the data portion of an update request.
type WinBackOfferUpdateData struct {
	Type       ResourceType                 `json:"type"`
	ID         string                       `json:"id"`
	Attributes WinBackOfferUpdateAttributes `json:"attributes"`
}

// WinBackOfferUpdateRequest is a request to update a win-back offer.
type WinBackOfferUpdateRequest struct {
	Data WinBackOfferUpdateData `json:"data"`
}

// WinBackOfferPriceAttributes describes a win-back offer price (attributes are empty).
type WinBackOfferPriceAttributes struct{}

// WinBackOfferPriceRelationships describes price relationships.
type WinBackOfferPriceRelationships struct {
	Territory              Relationship `json:"territory"`
	SubscriptionPricePoint Relationship `json:"subscriptionPricePoint"`
}

// WinBackOfferPriceInlineCreate describes inline creation data for prices.
// Win-back offer prices do not exist before the offer is created, so the
// create request must inline them via the JSON:API `included` array with
// temporary `${price-N}` IDs, each carrying territory and
// subscriptionPricePoint relationships. Without the relationships the API
// rejects the request with "Missing subscriptionPricePoint relationship".
type WinBackOfferPriceInlineCreate struct {
	Type          ResourceType                    `json:"type"`
	ID            string                          `json:"id,omitempty"`
	Relationships *WinBackOfferPriceRelationships `json:"relationships,omitempty"`
}

// WinBackOffersResponse is the response from list endpoints.
type WinBackOffersResponse = Response[WinBackOfferAttributes]

// WinBackOfferResponse is the response from detail endpoints.
type WinBackOfferResponse = SingleResponse[WinBackOfferAttributes]

// WinBackOfferPricesResponse is the response from prices endpoints.
type WinBackOfferPricesResponse = Response[WinBackOfferPriceAttributes]
