package signing

import (
	"bytes"
	"context"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/rudrankriyam/App-Store-Connect-CLI/internal/asc"
	"github.com/rudrankriyam/App-Store-Connect-CLI/internal/cli/shared"
	signingpkg "github.com/rudrankriyam/App-Store-Connect-CLI/internal/signing"
	"howett.net/plist"
)

func TestSigningSyncBatchProfilePathIsTargetScoped(t *testing.T) {
	got := signingSyncBatchProfilePath("com.example.app", "IOS_APP_STORE", "profile-123")
	want := filepath.Join("profiles", "appstore", "com.example.app--profile-123.mobileprovision")
	if got != want {
		t.Fatalf("signingSyncBatchProfilePath() = %q, want %q", got, want)
	}
}

func TestProfileCreateNameForTargetAcceptsOperationDateBoundary(t *testing.T) {
	createdAt := time.Date(2026, time.August, 30, 23, 59, 59, 0, time.Local)
	observedAt := createdAt.Add(2 * time.Second)
	got := profileCreateNameForTarget("IOS_APP_DEVELOPMENT", "com.example.new", createdAt)
	if got == profileCreateNameForTarget("IOS_APP_DEVELOPMENT", "com.example.new", observedAt) {
		t.Fatal("test fixture must cross a local date boundary")
	}
	if !profileCreateNameForTargetInTimeWindow(got, "IOS_APP_DEVELOPMENT", "com.example.new", createdAt, observedAt) {
		t.Fatalf("profile name %q was rejected for an operation spanning %s to %s", got, createdAt, observedAt)
	}
}

// profileCreateNameForTargetInTimeWindow keeps this integration assertion stable
// when resolving assets and publishing the repository crosses local midnight.
// The name is generated by production at an instant between these observations,
// so either boundary date is valid without adding a production clock seam.
func profileCreateNameForTargetInTimeWindow(got, profileType, bundleIdentifier string, startedAt, finishedAt time.Time) bool {
	if finishedAt.Before(startedAt) {
		startedAt, finishedAt = finishedAt, startedAt
	}
	return got == profileCreateNameForTarget(profileType, bundleIdentifier, startedAt) ||
		got == profileCreateNameForTarget(profileType, bundleIdentifier, finishedAt)
}

func TestSyncResultOmitsSingularBundleIDOnlyForBatchJSON(t *testing.T) {
	batchResult := SyncResult{
		Operation: "push",
		BundleID:  "com.example.app",
		BundleIDs: []string{"com.example.app"},
		Targets:   []SyncTargetResult{{BundleID: "com.example.app"}},
	}
	batchResult.MarkBatch()
	batchData, err := json.Marshal(batchResult)
	if err != nil {
		t.Fatal(err)
	}
	var batch map[string]any
	if err := json.Unmarshal(batchData, &batch); err != nil {
		t.Fatal(err)
	}
	if _, ok := batch["bundleId"]; ok {
		t.Fatalf("batch JSON unexpectedly contains singular bundleId: %s", batchData)
	}

	singleData, err := json.Marshal(SyncResult{Operation: "pull"})
	if err != nil {
		t.Fatal(err)
	}
	var single map[string]any
	if err := json.Unmarshal(singleData, &single); err != nil {
		t.Fatal(err)
	}
	if _, ok := single["bundleId"]; !ok {
		t.Fatalf("single JSON lost historical bundleId field: %s", singleData)
	}

	emptyBatchResult := SyncResult{Operation: "push", BundleID: "com.example.app"}
	emptyBatchResult.MarkBatch()
	emptyBatchData, err := json.Marshal(emptyBatchResult)
	if err != nil {
		t.Fatal(err)
	}
	var emptyBatch map[string]any
	if err := json.Unmarshal(emptyBatchData, &emptyBatch); err != nil {
		t.Fatal(err)
	}
	if _, ok := emptyBatch["bundleId"]; ok {
		t.Fatalf("empty batch JSON unexpectedly contains singular bundleId: %s", emptyBatchData)
	}
}

func TestSigningSyncPushRejectsInvalidOutputBeforeSideEffects(t *testing.T) {
	missingDir := t.TempDir()
	clientCalls := 0
	t.Cleanup(shared.SetASCClientFactoryForTesting(func() (*asc.Client, error) {
		clientCalls++
		return nil, errors.New("client must not be created")
	}))

	tests := []struct {
		name string
		args []string
		want string
	}{
		{
			name: "unsupported output",
			args: []string{
				"--targets-file", filepath.Join(missingDir, "missing-targets.json"),
				"--profile-type", "IOS_APP_STORE",
				"--repo", "file:///missing/signing.git",
				"--password-file", filepath.Join(missingDir, "missing-password"),
				"--private-key", filepath.Join(missingDir, "missing-key.pem"),
				"--identity-sha256", strings.Repeat("A", 64),
				"--output", "yaml",
			},
			want: `--output must be one of: json, table, markdown (got "yaml")`,
		},
		{
			name: "pretty with table",
			args: []string{
				"--targets-file", filepath.Join(missingDir, "missing-targets.json"),
				"--profile-type", "IOS_APP_STORE",
				"--repo", "file:///missing/signing.git",
				"--password-file", filepath.Join(missingDir, "missing-password"),
				"--private-key", filepath.Join(missingDir, "missing-key.pem"),
				"--identity-sha256", strings.Repeat("A", 64),
				"--output", "table",
				"--pretty",
			},
			want: "--pretty is only valid with JSON output",
		},
	}

	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			cmd := syncPushCommand()
			cmd.FlagSet.SetOutput(io.Discard)
			if err := cmd.Parse(testCase.args); err != nil {
				t.Fatal(err)
			}
			var runErr error
			stdout, stderr := captureOutput(t, func() {
				runErr = cmd.Run(context.Background())
			})
			if runErr == nil || !errors.Is(runErr, flag.ErrHelp) || !strings.Contains(runErr.Error(), testCase.want) {
				t.Fatalf("error = %v, want usage error containing %q", runErr, testCase.want)
			}
			if stdout != "" {
				t.Fatalf("stdout = %q, want empty", stdout)
			}
			if stderr != "Error: "+testCase.want+"\n" {
				t.Fatalf("stderr = %q, want only output validation diagnostic", stderr)
			}
		})
	}
	if clientCalls != 0 {
		t.Fatalf("client factory calls = %d, want 0", clientCalls)
	}
}

func TestSigningSyncPushTargetsFileValidationPrecedesPasswordAndClient(t *testing.T) {
	dir := t.TempDir()
	manifest := filepath.Join(dir, "targets.json")
	writeSigningSyncTargetsFile(t, manifest, `{"schemaVersion":1,"targets":[{"bundleId":"com.example.app"}],"unexpected":true}`, 0o644)
	t.Chdir(dir)
	clientCalls := 0
	t.Cleanup(shared.SetASCClientFactoryForTesting(func() (*asc.Client, error) {
		clientCalls++
		return nil, errors.New("client must not be created")
	}))

	cmd := syncPushCommand()
	cmd.FlagSet.SetOutput(io.Discard)
	if err := cmd.Parse([]string{
		"--targets-file", "targets.json",
		"--profile-type", "IOS_APP_STORE",
		"--repo", "git@example.com:team/signing.git",
	}); err != nil {
		t.Fatal(err)
	}
	var runErr error
	stdout, stderr := captureOutput(t, func() {
		runErr = cmd.Run(context.Background())
	})
	if runErr == nil || !errors.Is(runErr, flag.ErrHelp) || !strings.Contains(runErr.Error(), "unknown field") {
		t.Fatalf("targets manifest error = %v, want usage unknown-field error", runErr)
	}
	if stdout != "" {
		t.Fatalf("stdout = %q, want empty", stdout)
	}
	if !strings.Contains(stderr, "unknown field") {
		t.Fatalf("stderr = %q, want manifest diagnostic", stderr)
	}
	if clientCalls != 0 {
		t.Fatalf("client factory calls = %d, want 0", clientCalls)
	}
}

// runSigningSyncPushBatchForContext drives the push command down the batch
// branch with a stub runner and returns the context the runner received.
func runSigningSyncPushBatchForContext(t *testing.T, commandCtx context.Context) context.Context {
	t.Helper()
	dir := t.TempDir()
	writeSigningSyncTargetsFile(t, filepath.Join(dir, "targets.json"), `{"schemaVersion":1,"targets":[{"bundleId":"com.example.app"}]}`, 0o644)
	t.Chdir(dir)
	t.Setenv(signingSyncPasswordEnvVar, "repository-password")
	t.Setenv("ASC_TIMEOUT", "40ms")

	client := &asc.Client{}
	t.Cleanup(shared.SetASCClientFactoryForTesting(func() (*asc.Client, error) {
		return client, nil
	}))
	originalRunner := runSigningSyncBatchForCommand
	var received context.Context
	runSigningSyncBatchForCommand = func(ctx context.Context, gotClient *asc.Client, options signingSyncBatchOptions) (SyncResult, error) {
		received = ctx
		if gotClient != client {
			t.Errorf("batch client = %p, want %p", gotClient, client)
		}
		return SyncResult{}, context.Canceled
	}
	t.Cleanup(func() { runSigningSyncBatchForCommand = originalRunner })

	cmd := syncPushCommand()
	cmd.FlagSet.SetOutput(io.Discard)
	if err := cmd.Parse([]string{
		"--targets-file", "targets.json",
		"--profile-type", "IOS_APP_STORE",
		"--repo", "file:///unused/signing.git",
	}); err != nil {
		t.Fatal(err)
	}
	var runErr error
	stdout, _ := captureOutput(t, func() {
		runErr = cmd.Run(commandCtx)
	})
	if runErr == nil || runErr.Error() != "signing sync push: context canceled" {
		t.Fatalf("error = %v, want wrapped batch cancellation", runErr)
	}
	if stdout != "" {
		t.Fatalf("stdout = %q, want no success receipt after cancellation", stdout)
	}
	if received == nil {
		t.Fatal("batch runner was not called")
	}
	return received
}

// A multi-target batch performs one profile lookup, asset resolution, and
// optional profile creation per target, then clones and pushes the signing
// repository. Capping that whole sequence with a single per-request timeout
// fails valid runs, and with --create-missing it can abandon freshly created
// App Store Connect profiles before the repository commit is published.
func TestSigningSyncPushBatchDoesNotCapBatchWithOneRequestTimeout(t *testing.T) {
	received := runSigningSyncPushBatchForContext(t, context.Background())
	if deadline, ok := received.Deadline(); ok {
		t.Fatalf("batch runner deadline = %v (remaining %v), want the unbounded command context so per-request timeouts and Git publication are not capped by one request budget", deadline, time.Until(deadline))
	}
	requestCtx, cancel := shared.ContextWithTimeout(received)
	defer cancel()
	deadline, ok := requestCtx.Deadline()
	if !ok {
		t.Fatal("per-request context derived inside the batch has no deadline")
	}
	if remaining := time.Until(deadline); remaining <= 0 || remaining > 40*time.Millisecond {
		t.Fatalf("per-request deadline remaining = %v, want a full positive request timeout <= 40ms", remaining)
	}
}

func TestSigningSyncPushBatchPreservesOuterCommandDeadline(t *testing.T) {
	commandCtx, cancel := context.WithTimeout(context.Background(), time.Hour)
	defer cancel()
	received := runSigningSyncPushBatchForContext(t, commandCtx)
	deadline, ok := received.Deadline()
	if !ok {
		t.Fatal("batch runner dropped the caller's command deadline")
	}
	if remaining := time.Until(deadline); remaining <= 40*time.Millisecond {
		t.Fatalf("batch runner deadline remaining = %v, want the caller's hour-long budget rather than one request timeout", remaining)
	}
}

func TestSigningSyncPushRejectsBundleIDAndTargetsFileTogether(t *testing.T) {
	manifest := filepath.Join(t.TempDir(), "targets.json")
	writeSigningSyncTargetsFile(t, manifest, `{"schemaVersion":1,"targets":[{"bundleId":"com.example.app"}]}`, 0o644)
	cmd := syncPushCommand()
	if err := cmd.Parse([]string{
		"--bundle-id", "com.example.other",
		"--targets-file", manifest,
		"--profile-type", "IOS_APP_STORE",
		"--repo", "git@example.com:team/signing.git",
	}); err != nil {
		t.Fatal(err)
	}
	err := cmd.Run(context.Background())
	if err == nil || !errors.Is(err, flag.ErrHelp) || err.Error() != "--bundle-id and --targets-file are mutually exclusive" {
		t.Fatalf("error = %v, want mutual-exclusion usage error", err)
	}
}

func TestSigningSyncLegacyArtifactSemanticNoOpAndFailClosed(t *testing.T) {
	store := &signingpkg.GitStore{LocalDir: t.TempDir()}
	password := "repository-password"
	path := filepath.Join("certs", "distribution", "certificate.cer")
	wanted := []byte("certificate-content")
	if err := store.WriteEncryptedFile(path, wanted, password); err != nil {
		t.Fatal(err)
	}
	encryptedPath := filepath.Join(store.LocalDir, path+".enc")
	before, err := os.ReadFile(encryptedPath)
	if err != nil {
		t.Fatal(err)
	}
	if same, err := preflightSigningSyncLegacyArtifact(store, path, wanted, password); err != nil || !same {
		t.Fatalf("preflight same artifact = same:%v err:%v, want same", same, err)
	}
	if err := writeOrReuseSigningSyncLegacyArtifact(store, path, wanted, password); err != nil {
		t.Fatal(err)
	}
	after, err := os.ReadFile(encryptedPath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("semantic no-op rewrote legacy ciphertext")
	}

	if _, err := preflightSigningSyncLegacyArtifact(store, path, wanted, "wrong-password"); err == nil || !strings.Contains(err.Error(), "cannot be authenticated") {
		t.Fatalf("wrong-password preflight error = %v, want fail-closed authentication error", err)
	}

	versionedPath := filepath.Join("profiles", "appstore", "profile.mobileprovision")
	if err := store.WriteEncryptedFileWithMetadata(versionedPath, wanted, password, signingpkg.EncryptedFileMetadata{
		Kind:      "unexpected-kind",
		Sensitive: false,
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := preflightSigningSyncLegacyArtifact(store, versionedPath, wanted, password); err == nil || !strings.Contains(err.Error(), "incompatible authenticated metadata") {
		t.Fatalf("versioned legacy-artifact preflight error = %v, want incompatible metadata error", err)
	}
}

func TestPrepareSigningSyncBatchFilesDeduplicatesCertificates(t *testing.T) {
	store := &signingpkg.GitStore{LocalDir: t.TempDir()}
	profileContentA := base64.StdEncoding.EncodeToString([]byte("profile-a"))
	profileContentB := base64.StdEncoding.EncodeToString([]byte("profile-b"))
	certificateContent := base64.StdEncoding.EncodeToString([]byte("certificate"))
	certificate := asc.Resource[asc.CertificateAttributes]{
		ID: "certificate-1",
		Attributes: asc.CertificateAttributes{
			SerialNumber:       "serial-1",
			CertificateContent: certificateContent,
		},
	}
	targets := []signingSyncBatchTarget{
		{
			BundleID:    "com.example.b",
			ProfileType: "IOS_APP_STORE",
			Profile: &asc.ProfileResponse{Data: asc.Resource[asc.ProfileAttributes]{
				ID:         "profile-b",
				Attributes: asc.ProfileAttributes{ProfileContent: profileContentB},
			}},
			Certificates: []asc.Resource[asc.CertificateAttributes]{certificate},
		},
		{
			BundleID:    "com.example.a",
			ProfileType: "IOS_APP_STORE",
			Profile: &asc.ProfileResponse{Data: asc.Resource[asc.ProfileAttributes]{
				ID:         "profile-a",
				Attributes: asc.ProfileAttributes{ProfileContent: profileContentA},
			}},
			Certificates: []asc.Resource[asc.CertificateAttributes]{certificate},
		},
	}
	files, _, err := prepareSigningSyncBatchFiles(store, targets, nil, "password")
	if err != nil {
		t.Fatalf("prepareSigningSyncBatchFiles() error = %v", err)
	}
	if len(files) != 3 {
		t.Fatalf("planned legacy files = %d, want two profiles and one certificate: %#v", len(files), files)
	}
	if got := files[0].RelativePath; got != filepath.Join("certs", "distribution", "serial-1.cer") {
		t.Fatalf("first planned path = %q, want certificate path", got)
	}
	if files[0].Profile != nil || files[1].Profile == nil || files[2].Profile == nil {
		t.Fatalf("planned metadata = %#v, want legacy certificate and authenticated profiles", files)
	}
	if got := len(targets[0].Files); got != 2 {
		t.Fatalf("first target files = %d, want profile plus deduplicated certificate", got)
	}
	if got := len(targets[1].Files); got != 2 {
		t.Fatalf("second target files = %d, want profile plus deduplicated certificate", got)
	}
}

func TestPrepareSigningSyncBatchFilesBindsIdentityContextsToTargetScopedProfiles(t *testing.T) {
	key := mustECKey(t)
	certificate := mustSigningCertificate(t, key, 101)
	identity := &signingIdentity{PrivateKey: key, Certificate: certificate, CertificateSHA256: certificateSHA256(certificate)}
	certificateResource := asc.Resource[asc.CertificateAttributes]{
		ID: "certificate-shared",
		Attributes: asc.CertificateAttributes{
			CertificateType:    "IOS_DISTRIBUTION",
			CertificateContent: base64.StdEncoding.EncodeToString(certificate.Raw),
			ExpirationDate:     certificate.NotAfter.Format(time.RFC3339),
			Activated:          boolPointer(true),
			SerialNumber:       "shared-serial",
		},
	}
	targets := make([]signingSyncBatchTarget, 0, 2)
	for _, target := range []struct {
		bundleID  string
		profileID string
	}{
		{bundleID: "com.example.a", profileID: "profile-a"},
		{bundleID: "com.example.b", profileID: "profile-b"},
	} {
		profileContent := batchIdentityProfileContent(t, certificate, key, target.bundleID)
		targets = append(targets, signingSyncBatchTarget{
			BundleID:    target.bundleID,
			ProfileType: "IOS_APP_ADHOC",
			Profile: &asc.ProfileResponse{Data: asc.Resource[asc.ProfileAttributes]{
				ID: target.profileID,
				Attributes: asc.ProfileAttributes{
					ProfileType:    "IOS_APP_ADHOC",
					ProfileState:   asc.ProfileStateActive,
					ProfileContent: base64.StdEncoding.EncodeToString(profileContent),
					UUID:           "01234567-89ab-cdef-0123-456789abcdef",
				},
			}},
			Certificates: []asc.Resource[asc.CertificateAttributes]{certificateResource},
		})
	}

	store := &signingpkg.GitStore{LocalDir: t.TempDir()}
	legacyFiles, identityCore, err := prepareSigningSyncBatchFiles(store, targets, identity, "repository-password")
	if err != nil {
		t.Fatalf("prepareSigningSyncBatchFiles() error = %v", err)
	}
	if identityCore == "" || len(legacyFiles) != 3 {
		t.Fatalf("identity core=%q legacy files=%d, want one core and three public files", identityCore, len(legacyFiles))
	}
	if targets[0].IdentityArtifacts.IdentityPath != targets[1].IdentityArtifacts.IdentityPath {
		t.Fatalf("identity core paths differ: %q vs %q", targets[0].IdentityArtifacts.IdentityPath, targets[1].IdentityArtifacts.IdentityPath)
	}
	if targets[0].IdentityArtifacts.BindingPath == targets[1].IdentityArtifacts.BindingPath {
		t.Fatal("identity context paths were not target-scoped")
	}
	for _, target := range targets {
		var binding identityContextBinding
		if err := json.Unmarshal(target.IdentityArtifacts.BindingData, &binding); err != nil {
			t.Fatal(err)
		}
		if binding.ProfilePath != filepath.ToSlash(target.ProfilePath) {
			t.Fatalf("binding profile path = %q, target path = %q", binding.ProfilePath, target.ProfilePath)
		}
		if !strings.Contains(target.ProfilePath, target.BundleID+"--") {
			t.Fatalf("profile path %q is not target-scoped", target.ProfilePath)
		}
	}
}

func TestPrepareSigningSyncBatchFilesRejectsConflictingCertificateBytes(t *testing.T) {
	store := &signingpkg.GitStore{LocalDir: t.TempDir()}
	targets := make([]signingSyncBatchTarget, 2)
	for index, certificateContent := range []string{"first-certificate", "second-certificate"} {
		targets[index] = signingSyncBatchTarget{
			BundleID:    fmt.Sprintf("com.example.%c", 'a'+rune(index)),
			ProfileType: "IOS_APP_STORE",
			Profile: &asc.ProfileResponse{Data: asc.Resource[asc.ProfileAttributes]{
				ID: fmt.Sprintf("profile-%d", index+1),
				Attributes: asc.ProfileAttributes{
					ProfileContent: base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("profile-%d", index+1))),
				},
			}},
			Certificates: []asc.Resource[asc.CertificateAttributes]{{
				ID: "certificate-shared",
				Attributes: asc.CertificateAttributes{
					SerialNumber:       "shared-serial",
					CertificateContent: base64.StdEncoding.EncodeToString([]byte(certificateContent)),
				},
			}},
		}
	}

	_, _, err := prepareSigningSyncBatchFiles(store, targets, nil, "repository-password")
	if err == nil || !strings.Contains(err.Error(), "certificate certificate-shared returned conflicting content") {
		t.Fatalf("prepareSigningSyncBatchFiles() error = %v, want conflicting certificate content", err)
	}
}

func TestRunSigningSyncBatchCreatesOneCommitAndIsIdempotent(t *testing.T) {
	remoteURL, remotePath := newSigningSyncBareRemote(t)
	password := "repository-password"
	profileBodies := map[string]string{
		"profile-a": base64.StdEncoding.EncodeToString([]byte("profile-a-content")),
		"profile-b": base64.StdEncoding.EncodeToString([]byte("profile-b-content")),
	}
	certificateContent := base64.StdEncoding.EncodeToString([]byte("shared-certificate-content"))
	requests := make([]string, 0)
	client := newSigningFetchTestClient(t, func(req *http.Request) *http.Response {
		requests = append(requests, req.Method+" "+req.URL.Path)
		switch {
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds":
			identifier := req.URL.Query().Get("filter[identifier]")
			resourceID := map[string]string{"com.example.a": "bundle-a", "com.example.b": "bundle-b"}[identifier]
			if resourceID == "" {
				t.Fatalf("unexpected bundle identifier filter %q", identifier)
			}
			return signingFetchJSONResponse(http.StatusOK, fmt.Sprintf(`{"data":[{"type":"bundleIds","id":%q,"attributes":{"identifier":%q}}]}`, resourceID, identifier))
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/bundleIds/") && strings.HasSuffix(req.URL.Path, "/profiles"):
			bundleResourceID := strings.TrimSuffix(strings.TrimPrefix(req.URL.Path, "/v1/bundleIds/"), "/profiles")
			profileID := map[string]string{"bundle-a": "profile-a", "bundle-b": "profile-b"}[bundleResourceID]
			profileContent := profileBodies[profileID]
			return signingFetchJSONResponse(http.StatusOK, fmt.Sprintf(`{"data":[{"type":"profiles","id":%q,"attributes":{"name":%q,"profileType":"IOS_APP_STORE","profileState":"ACTIVE","profileContent":%q}}]}`, profileID, profileID, profileContent))
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/profiles/") && strings.HasSuffix(req.URL.Path, "/certificates"):
			return signingFetchJSONResponse(http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-shared","attributes":{"serialNumber":"shared-serial","certificateType":"IOS_DISTRIBUTION","expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		default:
			t.Fatalf("unexpected request %s %s", req.Method, req.URL.String())
			return signingFetchJSONResponse(http.StatusInternalServerError, `{}`)
		}
	})

	bundleIDs := []string{"com.example.a", "com.example.b"}
	var result SyncResult
	var err error
	_, firstStderr := captureOutput(t, func() {
		result, err = runSigningSyncBatch(context.Background(), client, signingSyncBatchOptions{
			RepoURL:     remoteURL,
			Password:    password,
			ProfileType: "IOS_APP_STORE",
			BundleIDs:   bundleIDs,
		})
	})
	if err != nil {
		t.Fatalf("first batch push error = %v", err)
	}
	if got := strings.Count(firstStderr, "Cloning signing repo..."); got != 1 {
		t.Fatalf("first batch clone progress count = %d, want 1\n%s", got, firstStderr)
	}
	if got, want := len(result.Targets), 2; got != want {
		t.Fatalf("target result count = %d, want %d", got, want)
	}
	if got, want := len(result.Files), 3; got != want {
		t.Fatalf("top-level file union count = %d, want %d", got, want)
	}
	bundleLookups := 0
	for _, request := range requests {
		if request == "GET /v1/bundleIds" {
			bundleLookups++
		}
	}
	if got := bundleLookups; got != 2 {
		t.Fatalf("bundle lookup count = %d, want 2", got)
	}
	if got := gitOutput(t, remotePath, "rev-list", "--count", "main"); strings.TrimSpace(got) != "2" {
		t.Fatalf("remote commit count after first push = %q, want 2", got)
	}

	var second SyncResult
	_, secondStderr := captureOutput(t, func() {
		second, err = runSigningSyncBatch(context.Background(), client, signingSyncBatchOptions{
			RepoURL:     remoteURL,
			Password:    password,
			ProfileType: "IOS_APP_STORE",
			BundleIDs:   bundleIDs,
		})
	})
	if err != nil {
		t.Fatalf("second batch push error = %v", err)
	}
	if got := strings.Count(secondStderr, "Cloning signing repo..."); got != 1 {
		t.Fatalf("second batch clone progress count = %d, want 1\n%s", got, secondStderr)
	}
	if !bytes.Equal(mustJSON(t, result.Files), mustJSON(t, second.Files)) {
		t.Fatalf("idempotent file union changed: first=%v second=%v", result.Files, second.Files)
	}
	if got := gitOutput(t, remotePath, "rev-list", "--count", "main"); strings.TrimSpace(got) != "2" {
		t.Fatalf("remote commit count after idempotent push = %q, want unchanged 2", got)
	}

	files := gitOutput(t, remotePath, "ls-tree", "-r", "--name-only", "main")
	if got := strings.Count(files, "certs/distribution/shared-serial.cer.enc"); got != 1 {
		t.Fatalf("shared certificate repository entries = %d, want 1\n%s", got, files)
	}
	for _, profileID := range []string{"profile-a", "profile-b"} {
		want := "profiles/appstore/com.example." + strings.TrimPrefix(profileID, "profile-") + "--" + profileID + ".mobileprovision.enc"
		if !strings.Contains(files, want) {
			t.Fatalf("repository tree missing target-scoped profile %q\n%s", want, files)
		}
	}
	cloneRoot := t.TempDir()
	checkout := filepath.Join(cloneRoot, "checkout")
	runGitCommand(t, cloneRoot, "clone", remotePath, checkout)
	stored := &signingpkg.GitStore{LocalDir: checkout}
	for _, suffix := range []string{"a", "b"} {
		profileID := "profile-" + suffix
		profilePath := filepath.Join("profiles", "appstore", "com.example."+suffix+"--"+profileID+".mobileprovision")
		_, metadata, err := stored.ReadEncryptedFileWithMetadata(profilePath, password)
		if err != nil {
			t.Fatal(err)
		}
		if metadata.Kind != signingProfileArtifactKind || metadata.BundleID != "com.example."+suffix ||
			metadata.ProfileType != "IOS_APP_STORE" || metadata.ProfileResourceID != profileID {
			t.Fatalf("stored profile metadata = %+v", metadata)
		}
	}
}

func TestRunSigningSyncBatchCreatesMissingProfileAfterPreflight(t *testing.T) {
	remoteURL, remotePath := newSigningSyncBareRemote(t)
	certificateContent := base64.StdEncoding.EncodeToString([]byte("new-certificate-content"))
	profileContent := base64.StdEncoding.EncodeToString([]byte("new-profile-content"))
	postCalls := 0
	var postBody []byte
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		switch {
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds":
			signingFetchWriteJSON(t, w, http.StatusOK, `{"data":[{"type":"bundleIds","id":"bundle-new","attributes":{"identifier":"com.example.new"}}]}`)
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds/bundle-new/profiles":
			signingFetchWriteJSON(t, w, http.StatusOK, `{"data":[]}`)
		case req.Method == http.MethodGet && req.URL.Path == "/v1/certificates":
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-new","attributes":{"serialNumber":"new-serial","certificateType":"IOS_DEVELOPMENT","expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		case req.Method == http.MethodPost && req.URL.Path == "/v1/profiles":
			postCalls++
			var err error
			postBody, err = io.ReadAll(req.Body)
			if err != nil {
				t.Fatalf("read profile create request: %v", err)
			}
			signingFetchWriteJSON(t, w, http.StatusCreated, fmt.Sprintf(`{"data":{"type":"profiles","id":"profile-new","attributes":{"name":"IOS_APP_DEVELOPMENT-20990101","profileType":"IOS_APP_DEVELOPMENT","profileState":"ACTIVE","profileContent":%q}}}`, profileContent))
		default:
			t.Fatalf("unexpected request %s %s", req.Method, req.URL.String())
			signingFetchWriteJSON(t, w, http.StatusInternalServerError, `{}`)
		}
	}))
	defer server.Close()
	client := newSigningFetchServerTestClient(t, server)

	var result SyncResult
	var err error
	profileNameWindowStart := time.Now()
	_, stderr := captureOutput(t, func() {
		result, err = runSigningSyncBatch(context.Background(), client, signingSyncBatchOptions{
			RepoURL:       remoteURL,
			Password:      "repository-password",
			ProfileType:   "IOS_APP_DEVELOPMENT",
			CreateMissing: true,
			DeviceIDs:     []string{"device-new"},
			BundleIDs:     []string{"com.example.new"},
		})
	})
	profileNameWindowEnd := time.Now()
	if err != nil {
		t.Fatalf("missing-profile batch push error = %v", err)
	}
	if postCalls != 1 {
		t.Fatalf("profile POST calls = %d, want 1", postCalls)
	}
	var payload asc.ProfileCreateRequest
	if err := json.Unmarshal(postBody, &payload); err != nil {
		t.Fatalf("decode profile create request: %v", err)
	}
	if payload.Data.Type != asc.ResourceTypeProfiles {
		t.Fatalf("profile create type = %q, want %q", payload.Data.Type, asc.ResourceTypeProfiles)
	}
	if payload.Data.Attributes.ProfileType != "IOS_APP_DEVELOPMENT" {
		t.Fatalf("profile create profileType = %q, want IOS_APP_DEVELOPMENT", payload.Data.Attributes.ProfileType)
	}
	if !profileCreateNameForTargetInTimeWindow(payload.Data.Attributes.Name, "IOS_APP_DEVELOPMENT", "com.example.new", profileNameWindowStart, profileNameWindowEnd) {
		t.Fatalf("profile create name = %q, want target-specific IOS_APP_DEVELOPMENT name dated within operation window [%s, %s]", payload.Data.Attributes.Name, profileNameWindowStart, profileNameWindowEnd)
	}
	if payload.Data.Relationships == nil || payload.Data.Relationships.BundleID == nil {
		t.Fatal("profile create request is missing bundleId relationship")
	}
	if got := payload.Data.Relationships.BundleID.Data; got.Type != asc.ResourceTypeBundleIds || got.ID != "bundle-new" {
		t.Fatalf("profile create bundle relationship = %#v, want bundleIds:bundle-new", got)
	}
	if payload.Data.Relationships.Certificates == nil || len(payload.Data.Relationships.Certificates.Data) != 1 {
		t.Fatal("profile create request is missing its certificate relationship")
	}
	if got := payload.Data.Relationships.Certificates.Data[0]; got.Type != asc.ResourceTypeCertificates || got.ID != "certificate-new" {
		t.Fatalf("profile create certificate relationship = %#v, want certificates:certificate-new", got)
	}
	if payload.Data.Relationships.Devices == nil || len(payload.Data.Relationships.Devices.Data) != 1 {
		t.Fatal("profile create request is missing its device relationship")
	}
	if got := payload.Data.Relationships.Devices.Data[0]; got.Type != asc.ResourceTypeDevices || got.ID != "device-new" {
		t.Fatalf("profile create device relationship = %#v, want devices:device-new", got)
	}
	if len(result.Targets) != 1 || !result.Targets[0].ProfileCreated {
		t.Fatalf("target result = %#v, want one created profile", result.Targets)
	}
	if !strings.Contains(stderr, "Created new profile for com.example.new") {
		t.Fatalf("stderr = %q, want profile creation diagnostic", stderr)
	}
	if got := strings.TrimSpace(gitOutput(t, remotePath, "rev-list", "--count", "main")); got != "2" {
		t.Fatalf("remote commit count = %q, want 2", got)
	}
	files := gitOutput(t, remotePath, "ls-tree", "-r", "--name-only", "main")
	if !strings.Contains(files, "certs/development/new-serial.cer.enc") || !strings.Contains(files, "profiles/development/com.example.new--profile-new.mobileprovision.enc") {
		t.Fatalf("remote tree missing created target artifacts:\n%s", files)
	}
}

func TestRunSigningSyncBatchCreatesTargetSpecificProfilesAndRetriesWithoutRecreating(t *testing.T) {
	remoteURL, remotePath := newSigningSyncBareRemote(t)
	certificateContent := base64.StdEncoding.EncodeToString([]byte("shared-certificate-content"))
	profileContent := base64.StdEncoding.EncodeToString([]byte("profile-content"))
	resourceIDs := map[string]string{
		"com.example.a": "bundle-a",
		"com.example.b": "bundle-b",
	}
	profileIDs := map[string]string{
		"bundle-a": "profile-a",
		"bundle-b": "profile-b",
	}
	createdNames := make(map[string]string)
	postCalls := 0

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		switch {
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds":
			identifier := req.URL.Query().Get("filter[identifier]")
			resourceID := resourceIDs[identifier]
			if resourceID == "" {
				t.Errorf("unexpected bundle identifier filter %q", identifier)
				signingFetchWriteJSON(t, w, http.StatusBadRequest, `{"errors":[{"title":"unexpected bundle"}]}`)
				return
			}
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"bundleIds","id":%q,"attributes":{"identifier":%q}}]}`, resourceID, identifier))
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/bundleIds/") && strings.HasSuffix(req.URL.Path, "/profiles"):
			bundleResourceID := strings.TrimSuffix(strings.TrimPrefix(req.URL.Path, "/v1/bundleIds/"), "/profiles")
			profileID := profileIDs[bundleResourceID]
			if name, ok := createdNames[bundleResourceID]; ok {
				signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"profiles","id":%q,"attributes":{"name":%q,"profileType":"IOS_APP_STORE","profileState":"ACTIVE","profileContent":%q}}]}`, profileID, name, profileContent))
				return
			}
			signingFetchWriteJSON(t, w, http.StatusOK, `{"data":[]}`)
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/profiles/") && strings.HasSuffix(req.URL.Path, "/certificates"):
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-shared","attributes":{"serialNumber":"shared-serial","certificateType":"IOS_DISTRIBUTION","expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		case req.Method == http.MethodGet && req.URL.Path == "/v1/certificates":
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-shared","attributes":{"serialNumber":"shared-serial","certificateType":"IOS_DISTRIBUTION","activated":true,"expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		case req.Method == http.MethodPost && req.URL.Path == "/v1/profiles":
			var payload asc.ProfileCreateRequest
			if err := json.NewDecoder(req.Body).Decode(&payload); err != nil {
				t.Errorf("decode profile create request: %v", err)
				signingFetchWriteJSON(t, w, http.StatusBadRequest, `{"errors":[{"title":"invalid request"}]}`)
				return
			}
			if payload.Data.Relationships == nil || payload.Data.Relationships.BundleID == nil {
				t.Errorf("profile create request is missing bundle relationship")
				signingFetchWriteJSON(t, w, http.StatusBadRequest, `{"errors":[{"title":"missing bundle"}]}`)
				return
			}
			bundleResourceID := payload.Data.Relationships.BundleID.Data.ID
			if _, ok := profileIDs[bundleResourceID]; !ok {
				t.Errorf("unexpected profile create bundle relationship %q", bundleResourceID)
				signingFetchWriteJSON(t, w, http.StatusBadRequest, `{"errors":[{"title":"unexpected bundle"}]}`)
				return
			}
			postCalls++
			createdNames[bundleResourceID] = payload.Data.Attributes.Name
			signingFetchWriteJSON(t, w, http.StatusCreated, fmt.Sprintf(`{"data":{"type":"profiles","id":%q,"attributes":{"name":%q,"profileType":"IOS_APP_STORE","profileState":"ACTIVE","profileContent":%q}}}`, profileIDs[bundleResourceID], payload.Data.Attributes.Name, profileContent))
		default:
			t.Errorf("unexpected request %s %s", req.Method, req.URL.String())
			signingFetchWriteJSON(t, w, http.StatusNotFound, `{"errors":[{"title":"unexpected request"}]}`)
		}
	}))
	defer server.Close()
	client := newSigningFetchServerTestClient(t, server)
	options := signingSyncBatchOptions{
		RepoURL:       remoteURL,
		Password:      "repository-password",
		ProfileType:   "IOS_APP_STORE",
		CreateMissing: true,
		BundleIDs:     []string{"com.example.b", "com.example.a"},
	}

	var first SyncResult
	var err error
	_, _ = captureOutput(t, func() {
		first, err = runSigningSyncBatch(context.Background(), client, options)
	})
	if err != nil {
		t.Fatalf("first batch push error = %v", err)
	}
	if got, want := postCalls, 2; got != want {
		t.Fatalf("first profile POST calls = %d, want %d", got, want)
	}
	if got := createdNames["bundle-a"]; got == "" || !strings.Contains(got, "com.example.a") {
		t.Fatalf("profile name for target A = %q, want target-specific component", got)
	}
	if got := createdNames["bundle-b"]; got == "" || !strings.Contains(got, "com.example.b") {
		t.Fatalf("profile name for target B = %q, want target-specific component", got)
	}
	if createdNames["bundle-a"] == createdNames["bundle-b"] {
		t.Fatalf("profile names collided: %q", createdNames["bundle-a"])
	}
	if got, want := len(first.Targets), 2; got != want {
		t.Fatalf("first target result count = %d, want %d", got, want)
	}

	var second SyncResult
	_, _ = captureOutput(t, func() {
		second, err = runSigningSyncBatch(context.Background(), client, options)
	})
	if err != nil {
		t.Fatalf("retry batch push error = %v", err)
	}
	if got, want := postCalls, 2; got != want {
		t.Fatalf("retry profile POST calls = %d, want unchanged %d", got, want)
	}
	if !bytes.Equal(mustJSON(t, first.Files), mustJSON(t, second.Files)) {
		t.Fatalf("retry file union changed: first=%v second=%v", first.Files, second.Files)
	}
	if got := strings.TrimSpace(gitOutput(t, remotePath, "rev-list", "--count", "main")); got != "2" {
		t.Fatalf("remote commit count after retry = %q, want unchanged 2", got)
	}
}

func TestRunSigningSyncBatchLaterTargetFailureDoesNotPublishPartialRepository(t *testing.T) {
	remoteURL, remotePath := newSigningSyncBareRemote(t)
	certificateContent := base64.StdEncoding.EncodeToString([]byte("first-certificate-content"))
	profileContent := base64.StdEncoding.EncodeToString([]byte("first-profile-content"))
	postCalls := 0
	certificateCalls := 0
	client := newSigningFetchTestClient(t, func(req *http.Request) *http.Response {
		switch {
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds":
			identifier := req.URL.Query().Get("filter[identifier]")
			resourceID := map[string]string{"com.example.a": "bundle-a", "com.example.b": "bundle-b"}[identifier]
			if resourceID == "" {
				t.Fatalf("unexpected bundle identifier filter %q", identifier)
			}
			return signingFetchJSONResponse(http.StatusOK, fmt.Sprintf(`{"data":[{"type":"bundleIds","id":%q,"attributes":{"identifier":%q}}]}`, resourceID, identifier))
		case req.Method == http.MethodGet && (req.URL.Path == "/v1/bundleIds/bundle-a/profiles" || req.URL.Path == "/v1/bundleIds/bundle-b/profiles"):
			return signingFetchJSONResponse(http.StatusOK, `{"data":[]}`)
		case req.Method == http.MethodGet && req.URL.Path == "/v1/certificates":
			certificateCalls++
			if certificateCalls > 1 {
				return signingFetchJSONResponse(http.StatusInternalServerError, `{"errors":[{"status":"500","title":"certificate lookup unavailable"}]}`)
			}
			return signingFetchJSONResponse(http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-a","attributes":{"serialNumber":"serial-a","certificateType":"IOS_DISTRIBUTION","expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		case req.Method == http.MethodPost && req.URL.Path == "/v1/profiles":
			postCalls++
			return signingFetchJSONResponse(http.StatusCreated, fmt.Sprintf(`{"data":{"type":"profiles","id":"profile-a","attributes":{"name":"IOS_APP_STORE-20990101","profileType":"IOS_APP_STORE","profileState":"ACTIVE","profileContent":%q}}}`, profileContent))
		default:
			t.Fatalf("unexpected request %s %s", req.Method, req.URL.String())
			return signingFetchJSONResponse(http.StatusInternalServerError, `{}`)
		}
	})

	var err error
	_, _ = captureOutput(t, func() {
		_, err = runSigningSyncBatch(context.Background(), client, signingSyncBatchOptions{
			RepoURL:       remoteURL,
			Password:      "repository-password",
			ProfileType:   "IOS_APP_STORE",
			CreateMissing: true,
			BundleIDs:     []string{"com.example.b", "com.example.a"},
		})
	})
	if err == nil {
		t.Fatal("later target failure unexpectedly succeeded")
	}
	if !strings.Contains(err.Error(), "com.example.b") ||
		!strings.Contains(err.Error(), "repository publication did not complete") ||
		!strings.Contains(err.Error(), "earlier App Store Connect profile creations may remain") {
		t.Fatalf("later target failure = %v, want failed target and partial-publication warning", err)
	}
	if postCalls != 1 {
		t.Fatalf("profile POST calls = %d, want only first target created", postCalls)
	}
	if got := strings.TrimSpace(gitOutput(t, remotePath, "rev-list", "--count", "main")); got != "1" {
		t.Fatalf("remote commit count after failed batch = %q, want seed commit only", got)
	}
}

func TestRunSigningSyncBatchUsesFreshTimeoutForEachTarget(t *testing.T) {
	remoteURL, _ := newSigningSyncBareRemote(t)
	certificateContent := base64.StdEncoding.EncodeToString([]byte("shared-certificate-content"))
	profileContent := base64.StdEncoding.EncodeToString([]byte("profile-content"))
	profileIDs := map[string]string{"bundle-a": "profile-a", "bundle-b": "profile-b"}
	timeoutCalls := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		switch {
		case req.Method == http.MethodGet && req.URL.Path == "/v1/bundleIds":
			identifier := req.URL.Query().Get("filter[identifier]")
			if identifier != "com.example.a" && identifier != "com.example.b" {
				t.Fatalf("unexpected bundle identifier filter %q", identifier)
			}
			// This delay is shorter than the first test timeout but long enough
			// that reusing it for the second target would exhaust the budget.
			time.Sleep(100 * time.Millisecond)
			resourceID := map[string]string{"com.example.a": "bundle-a", "com.example.b": "bundle-b"}[identifier]
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"bundleIds","id":%q,"attributes":{"identifier":%q}}]}`, resourceID, identifier))
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/bundleIds/") && strings.HasSuffix(req.URL.Path, "/profiles"):
			bundleResourceID := strings.TrimSuffix(strings.TrimPrefix(req.URL.Path, "/v1/bundleIds/"), "/profiles")
			profileID := profileIDs[bundleResourceID]
			if profileID == "" {
				t.Fatalf("unexpected bundle resource ID %q", bundleResourceID)
			}
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"profiles","id":%q,"attributes":{"profileType":"IOS_APP_STORE","profileState":"ACTIVE","profileContent":%q}}]}`, profileID, profileContent))
		case req.Method == http.MethodGet && strings.HasPrefix(req.URL.Path, "/v1/profiles/") && strings.HasSuffix(req.URL.Path, "/certificates"):
			signingFetchWriteJSON(t, w, http.StatusOK, fmt.Sprintf(`{"data":[{"type":"certificates","id":"certificate-shared","attributes":{"serialNumber":"shared-serial","certificateType":"IOS_DISTRIBUTION","expirationDate":"2100-01-01T00:00:00Z","certificateContent":%q}}]}`, certificateContent))
		default:
			t.Fatalf("unexpected request %s %s", req.Method, req.URL.String())
			signingFetchWriteJSON(t, w, http.StatusInternalServerError, `{}`)
		}
	}))
	defer server.Close()
	client := newSigningFetchServerTestClient(t, server)

	var result SyncResult
	var err error
	_, _ = captureOutput(t, func() {
		result, err = runSigningSyncBatch(context.Background(), client, signingSyncBatchOptions{
			RepoURL:     remoteURL,
			Password:    "repository-password",
			ProfileType: "IOS_APP_STORE",
			BundleIDs:   []string{"com.example.a", "com.example.b"},
			ContextWithTimeout: func(parent context.Context) (context.Context, context.CancelFunc) {
				timeoutCalls++
				if timeoutCalls == 1 {
					return context.WithTimeout(parent, 200*time.Millisecond)
				}
				return context.WithTimeout(parent, time.Second)
			},
		})
	})
	if err != nil {
		t.Fatalf("multi-target batch with delayed independent lookups failed: %v", err)
	}
	if got, want := len(result.Targets), 2; got != want {
		t.Fatalf("target result count = %d, want %d", got, want)
	}
	if got, want := timeoutCalls, 4; got != want {
		t.Fatalf("timeout context calls = %d, want one bundle and asset budget per target (%d)", got, want)
	}
}

func TestRunSigningSyncBatchCancellationReachesHTTPAndDoesNotPublish(t *testing.T) {
	remoteURL, remotePath := newSigningSyncBareRemote(t)
	requestStarted := make(chan struct{})
	requestCanceled := make(chan struct{})
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodGet || req.URL.Path != "/v1/bundleIds" {
			t.Errorf("unexpected request %s %s", req.Method, req.URL.String())
			signingFetchWriteJSON(t, w, http.StatusNotFound, `{"errors":[{"title":"unexpected request"}]}`)
			return
		}
		select {
		case <-requestStarted:
		default:
			close(requestStarted)
		}
		<-req.Context().Done()
		close(requestCanceled)
	}))
	defer server.Close()
	client := newSigningFetchServerTestClient(t, server)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	resultDone := make(chan error, 1)
	go func() {
		_, err := runSigningSyncBatch(ctx, client, signingSyncBatchOptions{
			RepoURL:     remoteURL,
			Password:    "repository-password",
			ProfileType: "IOS_APP_STORE",
			BundleIDs:   []string{"com.example.app"},
		})
		resultDone <- err
	}()
	select {
	case <-requestStarted:
		cancel()
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for bundle lookup")
	}
	select {
	case <-requestCanceled:
	case <-time.After(time.Second):
		t.Fatal("HTTP server did not observe request cancellation")
	}
	select {
	case err := <-resultDone:
		if err == nil || !strings.Contains(err.Error(), "context canceled") {
			t.Fatalf("batch cancellation error = %v, want context cancellation", err)
		}
	case <-time.After(time.Second):
		t.Fatal("batch runner did not return after request cancellation")
	}
	if got := strings.TrimSpace(gitOutput(t, remotePath, "rev-list", "--count", "main")); got != "1" {
		t.Fatalf("remote commit count after cancellation = %q, want seed commit only", got)
	}
}

func TestSigningSyncGitFixtureDoesNotMutateCallingRepositoryConfig(t *testing.T) {
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	commonDirectory := strings.TrimSpace(runGitCommand(t, workingDirectory, "rev-parse", "--git-common-dir"))
	localDirectory := strings.TrimSpace(runGitCommand(t, workingDirectory, "rev-parse", "--git-dir"))
	commonConfig := absoluteGitPath(workingDirectory, commonDirectory, "config")
	localConfig := absoluteGitPath(workingDirectory, localDirectory, "config")
	before := make(map[string][]byte, 2)
	existed := make(map[string]bool, 2)
	for _, path := range []string{commonConfig, localConfig} {
		data, err := os.ReadFile(path)
		switch {
		case err == nil:
			before[path] = data
			existed[path] = true
		case errors.Is(err, os.ErrNotExist):
			existed[path] = false
		default:
			t.Fatalf("read calling repository config %s: %v", path, err)
		}
	}

	newSigningSyncBareRemote(t)

	for path, want := range before {
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read calling repository config after fixture setup %s: %v", path, err)
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("calling repository config changed at %s", path)
		}
	}
	if !existed[commonConfig] {
		t.Fatalf("calling repository common config %s is missing", commonConfig)
	}
	if !existed[localConfig] {
		if _, err := os.Stat(localConfig); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("calling worktree config unexpectedly appeared at %s: %v", localConfig, err)
		}
	}
}

func batchIdentityProfileContent(t *testing.T, certificate *x509.Certificate, key any, bundleID string) []byte {
	t.Helper()
	profilePlist, err := plist.Marshal(map[string]any{
		"UUID":                        "01234567-89ab-cdef-0123-456789abcdef",
		"TeamIdentifier":              []string{"TEAM123"},
		"ApplicationIdentifierPrefix": []string{"TEAM123"},
		"ExpirationDate":              time.Now().Add(time.Hour),
		"DeveloperCertificates":       [][]byte{certificate.Raw},
		"ProvisionedDevices":          []string{"DEVICE1"},
		"Entitlements": map[string]any{
			"application-identifier": "TEAM123." + bundleID,
			"get-task-allow":         false,
		},
	}, plist.XMLFormat)
	if err != nil {
		t.Fatal(err)
	}
	return mustSignedCMS(t, profilePlist, certificate, key)
}

func boolPointer(value bool) *bool {
	return &value
}

func newSigningSyncBareRemote(t *testing.T) (string, string) {
	t.Helper()
	configureSigningSyncGitEnvironment(t)
	root := t.TempDir()
	remote := filepath.Join(root, "remote.git")
	runGitCommand(t, root, "init", "--bare", "--initial-branch=main", remote)
	seed := filepath.Join(root, "seed")
	if err := os.MkdirAll(seed, 0o755); err != nil {
		t.Fatal(err)
	}
	runGitCommand(t, seed, "init", "--initial-branch=main")
	runGitCommand(t, seed, "config", "user.name", "Signing Sync Test")
	runGitCommand(t, seed, "config", "user.email", "signing-sync@example.invalid")
	if err := os.WriteFile(filepath.Join(seed, "README"), []byte("seed"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGitCommand(t, seed, "add", "README")
	runGitCommand(t, seed, "commit", "-m", "seed")
	runGitCommand(t, seed, "remote", "add", "origin", remote)
	runGitCommand(t, seed, "push", "-u", "origin", "main")
	return "file://" + remote, remote
}

func configureSigningSyncGitEnvironment(t *testing.T) {
	t.Helper()
	configDirectory := t.TempDir()
	globalConfig := filepath.Join(configDirectory, "global")
	systemConfig := filepath.Join(configDirectory, "system")
	if err := os.WriteFile(globalConfig, []byte("[user]\n\tname = Signing Sync Test\n\temail = signing-sync@example.invalid\n"), 0o600); err != nil {
		t.Fatalf("create task-local Git global config: %v", err)
	}
	if err := os.WriteFile(systemConfig, nil, 0o600); err != nil {
		t.Fatalf("create task-local Git system config: %v", err)
	}
	// GitStore subprocesses inherit these task-local files so commits in the
	// cloned fixture have an identity. The direct runGitCommand helper below
	// still strips all inherited GIT_* variables and supplies its own empty
	// config for each isolated read/setup command.
	t.Setenv("GIT_CONFIG_NOSYSTEM", "1")
	t.Setenv("GIT_CONFIG_GLOBAL", globalConfig)
	t.Setenv("GIT_CONFIG_SYSTEM", systemConfig)
}

func runGitCommand(t *testing.T, dir string, args ...string) string {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = dir
	command.Env = isolatedGitTestEnvironment(t, os.Environ())
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func isolatedGitTestEnvironment(t *testing.T, environment []string) []string {
	t.Helper()
	configDirectory := t.TempDir()
	globalConfig := filepath.Join(configDirectory, "global")
	systemConfig := filepath.Join(configDirectory, "system")
	for _, path := range []string{globalConfig, systemConfig} {
		if err := os.WriteFile(path, nil, 0o600); err != nil {
			t.Fatalf("create isolated git config %s: %v", path, err)
		}
	}

	filtered := make([]string, 0, len(environment)+4)
	for _, value := range environment {
		if strings.HasPrefix(value, "GIT_") {
			continue
		}
		filtered = append(filtered, value)
	}
	return append(
		filtered,
		"GIT_TERMINAL_PROMPT=0",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_CONFIG_GLOBAL="+globalConfig,
		"GIT_CONFIG_SYSTEM="+systemConfig,
	)
}

func absoluteGitPath(workingDirectory, base, name string) string {
	if !filepath.IsAbs(base) {
		base = filepath.Join(workingDirectory, base)
	}
	return filepath.Join(base, name)
}

func gitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return runGitCommand(t, dir, args...)
}

func mustJSON(t *testing.T, value any) []byte {
	t.Helper()
	data, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return data
}
