package ascterritory

import (
	"strings"
	"unicode"
	"unicode/utf8"
)

var territoryAliases = map[string]string{
	"uae":                                   "ARE",
	"uk":                                    "GBR",
	"united states of america":              "USA",
	"republic of korea":                     "KOR",
	"korea republic of":                     "KOR",
	"korea south":                           "KOR",
	"democratic people's republic of korea": "PRK",
	"korea north":                           "PRK",
	"taiwan province of china":              "TWN",
	"russian federation":                    "RUS",
	"bolivia plurinational state of":        "BOL",
	"venezuela bolivarian republic of":      "VEN",
	"iran islamic republic of":              "IRN",
	"moldova republic of":                   "MDA",
	"tanzania united republic of":           "TZA",
	"lao people's democratic republic":      "LAO",
	"viet nam":                              "VNM",
	"syrian arab republic":                  "SYR",
	"palestine state of":                    "PSE",
	"brunei darussalam":                     "BRN",
	"czechia":                               "CZE",
	"eswatini":                              "SWZ",
	"cape verde":                            "CPV",
	"curacao":                               "CUW",
	"kosovo":                                "XKS",
	"hong kong sar china":                   "HKG",
	"macao sar china":                       "MAC",
	"myanmar":                               "MMR",
	"turkiye":                               "TUR",
	"cote d ivoire":                         "CIV",
	"cote divoire":                          "CIV",
	"congo democratic republic of the":      "COD",
	"democratic republic of the congo":      "COD",
	"congo republic of the":                 "COG",
	"republic of the congo":                 "COG",
	"micronesia federated states of":        "FSM",
	"macedonia the former yugoslav republic of": "MKD",
	"north macedonia": "MKD",
}

var territoryAmbiguousAliases = map[string]struct{}{
	"congo":          {},
	"korea":          {},
	"virgin islands": {},
}

var supportedIDs = map[string]struct{}{
	"ABW": {},
	"AFG": {},
	"AGO": {},
	"AIA": {},
	"ALB": {},
	"AND": {},
	"ANT": {},
	"ARE": {},
	"ARG": {},
	"ARM": {},
	"ASM": {},
	"ATG": {},
	"AUS": {},
	"AUT": {},
	"AZE": {},
	"BDI": {},
	"BEL": {},
	"BEN": {},
	"BES": {},
	"BFA": {},
	"BGD": {},
	"BGR": {},
	"BHR": {},
	"BHS": {},
	"BIH": {},
	"BLR": {},
	"BLZ": {},
	"BMU": {},
	"BOL": {},
	"BRA": {},
	"BRB": {},
	"BRN": {},
	"BTN": {},
	"BWA": {},
	"CAF": {},
	"CAN": {},
	"CHE": {},
	"CHL": {},
	"CHN": {},
	"CIV": {},
	"CMR": {},
	"COD": {},
	"COG": {},
	"COK": {},
	"COL": {},
	"COM": {},
	"CPV": {},
	"CRI": {},
	"CUB": {},
	"CUW": {},
	"CXR": {},
	"CYM": {},
	"CYP": {},
	"CZE": {},
	"DEU": {},
	"DJI": {},
	"DMA": {},
	"DNK": {},
	"DOM": {},
	"DZA": {},
	"ECU": {},
	"EGY": {},
	"ERI": {},
	"ESP": {},
	"EST": {},
	"ETH": {},
	"FIN": {},
	"FJI": {},
	"FLK": {},
	"FRA": {},
	"FRO": {},
	"FSM": {},
	"GAB": {},
	"GBR": {},
	"GEO": {},
	"GGY": {},
	"GHA": {},
	"GIB": {},
	"GIN": {},
	"GLP": {},
	"GMB": {},
	"GNB": {},
	"GNQ": {},
	"GRC": {},
	"GRD": {},
	"GRL": {},
	"GTM": {},
	"GUF": {},
	"GUM": {},
	"GUY": {},
	"HKG": {},
	"HND": {},
	"HRV": {},
	"HTI": {},
	"HUN": {},
	"IDN": {},
	"IMN": {},
	"IND": {},
	"IRL": {},
	"IRQ": {},
	"ISL": {},
	"ISR": {},
	"ITA": {},
	"JAM": {},
	"JEY": {},
	"JOR": {},
	"JPN": {},
	"KAZ": {},
	"KEN": {},
	"KGZ": {},
	"KHM": {},
	"KIR": {},
	"KNA": {},
	"KOR": {},
	"KWT": {},
	"LAO": {},
	"LBN": {},
	"LBR": {},
	"LBY": {},
	"LCA": {},
	"LIE": {},
	"LKA": {},
	"LSO": {},
	"LTU": {},
	"LUX": {},
	"LVA": {},
	"MAC": {},
	"MAR": {},
	"MCO": {},
	"MDA": {},
	"MDG": {},
	"MDV": {},
	"MEX": {},
	"MHL": {},
	"MKD": {},
	"MLI": {},
	"MLT": {},
	"MMR": {},
	"MNE": {},
	"MNG": {},
	"MNP": {},
	"MOZ": {},
	"MRT": {},
	"MSR": {},
	"MTQ": {},
	"MUS": {},
	"MWI": {},
	"MYS": {},
	"MYT": {},
	"NAM": {},
	"NCL": {},
	"NER": {},
	"NFK": {},
	"NGA": {},
	"NIC": {},
	"NIU": {},
	"NLD": {},
	"NOR": {},
	"NPL": {},
	"NRU": {},
	"NZL": {},
	"OMN": {},
	"PAK": {},
	"PAN": {},
	"PER": {},
	"PHL": {},
	"PLW": {},
	"PNG": {},
	"POL": {},
	"PRI": {},
	"PRT": {},
	"PRY": {},
	"PSE": {},
	"PYF": {},
	"QAT": {},
	"REU": {},
	"ROU": {},
	"RUS": {},
	"RWA": {},
	"SAU": {},
	"SEN": {},
	"SGP": {},
	"SHN": {},
	"SLB": {},
	"SLE": {},
	"SLV": {},
	"SMR": {},
	"SOM": {},
	"SPM": {},
	"SRB": {},
	"SSD": {},
	"STP": {},
	"SUR": {},
	"SVK": {},
	"SVN": {},
	"SWE": {},
	"SWZ": {},
	"SXM": {},
	"SYC": {},
	"TCA": {},
	"TCD": {},
	"TGO": {},
	"THA": {},
	"TJK": {},
	"TKM": {},
	"TLS": {},
	"TON": {},
	"TTO": {},
	"TUN": {},
	"TUR": {},
	"TUV": {},
	"TWN": {},
	"TZA": {},
	"UGA": {},
	"UKR": {},
	"UMI": {},
	"URY": {},
	"USA": {},
	"UZB": {},
	"VAT": {},
	"VCT": {},
	"VEN": {},
	"VGB": {},
	"VIR": {},
	"VNM": {},
	"VUT": {},
	"WLF": {},
	"WSM": {},
	"XKS": {},
	"YEM": {},
	"ZAF": {},
	"ZMB": {},
	"ZWE": {},
}

func normalizeName(value string) string {
	trimmed := strings.TrimSpace(strings.ToLower(value))
	if trimmed == "" {
		return ""
	}

	var builder strings.Builder
	lastSpace := false
	for _, r := range trimmed {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(r)
			lastSpace = false
			continue
		}
		if !lastSpace {
			builder.WriteRune(' ')
			lastSpace = true
		}
	}

	fields := strings.Fields(builder.String())
	if len(fields) == 0 {
		return ""
	}

	collapsed := make([]string, 0, len(fields))
	var initialism strings.Builder
	flushInitialism := func() {
		if initialism.Len() == 0 {
			return
		}
		collapsed = append(collapsed, initialism.String())
		initialism.Reset()
	}

	for _, field := range fields {
		if utf8.RuneCountInString(field) == 1 {
			initialism.WriteString(field)
			continue
		}
		flushInitialism()
		collapsed = append(collapsed, field)
	}
	flushInitialism()

	return strings.Join(collapsed, " ")
}
